name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: install
      run: cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: test
      working-directory: ${{github.workspace}}/test/bin
      run: ./Neumann-Test --gtest_output=xml:results.xml

    - name: upload-library
      uses: actions/upload-artifact@v3
      with:
        name: library
        path: lib/*.a

    - name: upload-example
      uses: actions/upload-artifact@v3
      with:
        name: example
        path: example/bin/*

    - name: upload-test
      uses: actions/upload-artifact@v3
      with:
        name: test
        path: test/bin/results.xml

    
